/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.10.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./StardexToken.types";
import * as _1 from "./StardexToken.client";
import * as _2 from "./StardexToken.react-query";
import * as _3 from "./StardexCoinRegistry.types";
import * as _4 from "./StardexCoinRegistry.client";
import * as _5 from "./StardexCoinRegistry.react-query";
import * as _6 from "./StardexFactory.types";
import * as _7 from "./StardexFactory.client";
import * as _8 from "./StardexFactory.react-query";
import * as _9 from "./StardexPair.types";
import * as _10 from "./StardexPair.client";
import * as _11 from "./StardexPair.react-query";
import * as _12 from "./StardexPairStable.types";
import * as _13 from "./StardexPairStable.client";
import * as _14 from "./StardexPairStable.react-query";
import * as _15 from "./StardexPairConcentrated.types";
import * as _16 from "./StardexPairConcentrated.client";
import * as _17 from "./StardexPairConcentrated.react-query";
import * as _18 from "./StardexRouter.types";
import * as _19 from "./StardexRouter.client";
import * as _20 from "./StardexRouter.react-query";
import * as _21 from "./StardexStakeNative.types";
import * as _22 from "./StardexStakeNative.client";
import * as _23 from "./StardexStakeNative.react-query";
import * as _24 from "./StardexStakeRewards.types";
import * as _25 from "./StardexStakeRewards.client";
import * as _26 from "./StardexStakeRewards.react-query";
export namespace contracts {
  export const StardexToken = {
    ..._0,
    ..._1,
    ..._2
  };
  export const StardexCoinRegistry = {
    ..._3,
    ..._4,
    ..._5
  };
  export const StardexFactory = {
    ..._6,
    ..._7,
    ..._8
  };
  export const StardexPair = {
    ..._9,
    ..._10,
    ..._11
  };
  export const StardexPairStable = {
    ..._12,
    ..._13,
    ..._14
  };
  export const StardexPairConcentrated = {
    ..._15,
    ..._16,
    ..._17
  };
  export const StardexRouter = {
    ..._18,
    ..._19,
    ..._20
  };
  export const StardexStakeNative = {
    ..._21,
    ..._22,
    ..._23
  };
  export const StardexStakeRewards = {
    ..._24,
    ..._25,
    ..._26
  };
}